version = 0.1

[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "blog-muazothman-com"
s3_prefix = "blog-muazothman-com"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
resolve_s3 = true
image_repositories = []
