AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: Static blog hosting with S3 and CloudFront

Parameters:
  DomainName:
    Type: String
    Default: muazothman.com
    Description: Root domain name

  SubDomain:
    Type: String
    Default: blog
    Description: Subdomain for the blog

  CertificateArn:
    Type: String
    NoEcho: true
    Description: ACM Certificate ARN (must be in us-east-1 for CloudFront)

Resources:
  # S3 Bucket for static website hosting
  BlogBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "${SubDomain}.${DomainName}"
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: 404.html
      VersioningConfiguration:
        Status: Enabled
      Tags:
        - Key: Name
          Value: !Sub "${SubDomain}.${DomainName}"
        - Key: Project
          Value: Blog

  # Bucket Policy to allow CloudFront access
  BlogBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref BlogBucket
      PolicyDocument:
        Statement:
          - Sid: AllowCloudFrontServicePrincipal
            Effect: Allow
            Principal:
              Service: cloudfront.amazonaws.com
            Action: s3:GetObject
            Resource: !Sub "${BlogBucket.Arn}/*"
            Condition:
              StringEquals:
                AWS:SourceArn: !Sub "arn:aws:cloudfront::${AWS::AccountId}:distribution/${BlogDistribution}"

  # CloudFront Origin Access Control
  BlogOAC:
    Type: AWS::CloudFront::OriginAccessControl
    Properties:
      OriginAccessControlConfig:
        Name: !Sub "${SubDomain}.${DomainName}-OAC"
        OriginAccessControlOriginType: s3
        SigningBehavior: always
        SigningProtocol: sigv4

  # CloudFront Function to append index.html to directory requests
  IndexRewriteFunction:
    Type: AWS::CloudFront::Function
    Properties:
      Name: blog-muazothman-index-rewrite
      AutoPublish: true
      FunctionCode: |
        function handler(event) {
          var request = event.request;
          var uri = request.uri;

          // Check if URI is missing a file extension and doesn't end with /
          if (!uri.includes('.') && !uri.endsWith('/')) {
            request.uri = uri + '/index.html';
          }
          // Check if URI ends with /
          else if (uri.endsWith('/')) {
            request.uri = uri + 'index.html';
          }

          return request;
        }
      FunctionConfig:
        Comment: Append index.html to directory-style requests
        Runtime: cloudfront-js-2.0

  # CloudFront Distribution
  BlogDistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Enabled: true
        HttpVersion: http2and3
        IPV6Enabled: true
        DefaultRootObject: index.html
        Aliases:
          - !Sub "${SubDomain}.${DomainName}"
        Origins:
          - Id: S3Origin
            DomainName: !GetAtt BlogBucket.RegionalDomainName
            S3OriginConfig:
              OriginAccessIdentity: ""
            OriginAccessControlId: !Ref BlogOAC
        DefaultCacheBehavior:
          TargetOriginId: S3Origin
          ViewerProtocolPolicy: redirect-to-https
          AllowedMethods:
            - GET
            - HEAD
            - OPTIONS
          CachedMethods:
            - GET
            - HEAD
          Compress: true
          CachePolicyId: 658327ea-f89d-4fab-a63d-7e88639e58f6 # CachingOptimized
          OriginRequestPolicyId: 88a5eaf4-2fd4-4709-b370-b4c650ea3fcf # CORS-S3Origin
          FunctionAssociations:
            - EventType: viewer-request
              FunctionARN: !GetAtt IndexRewriteFunction.FunctionMetadata.FunctionARN
        CustomErrorResponses:
          - ErrorCode: 403
            ResponseCode: 404
            ResponsePagePath: /404.html
          - ErrorCode: 404
            ResponseCode: 404
            ResponsePagePath: /404.html
        ViewerCertificate:
          AcmCertificateArn: !Ref CertificateArn
          MinimumProtocolVersion: TLSv1.2_2021
          SslSupportMethod: sni-only
        PriceClass: PriceClass_100
      Tags:
        - Key: Name
          Value: !Sub "${SubDomain}.${DomainName}"
        - Key: Project
          Value: Blog

  # Route53 DNS Record
  BlogDNSRecord:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneName: !Sub "${DomainName}."
      Name: !Sub "${SubDomain}.${DomainName}"
      Type: A
      AliasTarget:
        HostedZoneId: Z2FDTNDATAQYW2 # CloudFront hosted zone ID (constant)
        DNSName: !GetAtt BlogDistribution.DomainName

Outputs:
  BucketName:
    Description: S3 Bucket Name
    Value: !Ref BlogBucket
    Export:
      Name: !Sub "${AWS::StackName}-BucketName"

  DistributionId:
    Description: CloudFront Distribution ID
    Value: !Ref BlogDistribution
    Export:
      Name: !Sub "${AWS::StackName}-DistributionId"

  DistributionDomainName:
    Description: CloudFront Distribution Domain Name
    Value: !GetAtt BlogDistribution.DomainName
    Export:
      Name: !Sub "${AWS::StackName}-DistributionDomainName"

  WebsiteURL:
    Description: Website URL
    Value: !Sub "https://${SubDomain}.${DomainName}"
    Export:
      Name: !Sub "${AWS::StackName}-WebsiteURL"
